### ISSUE TITLE
error while treebuilding

### ISSUE THREAD

**Issue by timchu90** [McGranahanLab/CONIPHER#10]
Hi, 

I was able to run the clustering step successfully but am running into an error early into the treebuilding.

> [1] "Calculating cluster confidence intervals using bootstrapping"
> Error in t.default(do.call(rbind, lapply(pycloneCCF, function(x) { : 
>   argument is not a matrix
> Calls: conipher_treebuilding ... determine.cluster.nesting -> calc.pyclone.ci -> t -> t.default

the input matrix is straight from the clustering step "*.SCoutput.CLEAN.tsv"
any guidance as to solving this would be really appreciated!

Thanks!

**Comment by EsterAH89** [comment]
Hello, I have the same issue, for me it was a problem with the "CASE_ID" and "SAMPLE NAME", I have changed them and used somthing similiar to the one use in the toy_tsv and it worked. Hope it helps!

**Comment by timchu90** [comment]
Thanks! looks like that was it! To clarify, the CASE_ID and SAMPLE columns need to share the same prefix string. 
Seems like I missed this comment in the protocol paper. Thanks for your help
