### ISSUE TITLE
Chromosomes X and Y are ignored 

### ISSUE THREAD

**Issue by EsterAH89** [McGranahanLab/CONIPHER#11]
Hello everyone and thank for the CONIPHER tool!
I have a question regarding the input file, why are chromosome X and Y ignored as it is mentioned in your manuscript? Is there any reason behind? Is there any way to include them? Since I am analyzing some cases in which it would be very important to have them included.

Thanks in advanced!
Ester

**Comment by tobyaicher** [comment]
Hi,

I wanted to ask the same question: Is there any reason why chromosome X and Y are ignored and is there any way to include them? I see this comment was closed but was curious about the response.

Thanks!
TA

**Comment by EsterAH89** [comment]
Hello, 
I closed the issue because I asked directly to the authors and they told me they will update the code including this chromosomes. Apparently they were excluded because CN tools are not reliable in these chromosomes (I was not aware of that), but they are working in getting the code updated including them in a new version of the tool, I hope it will be available soon :)

For more info write them directly, they were very helpful,
Best wishes,

Ester
