### ISSUE TITLE
Clarifying Question about Input File

### ISSUE THREAD

**Issue by aseo714** [McGranahanLab/CONIPHER#2]
Hello,

I have a question regarding the input file of mutations for CONIPHER. I know in the original PyClone paper/implementation, if you have multiple samples from the same patient, it was advised to take a union set of mutations from each sample and add in read counts from bam files in tumor regions in samples that did not have a "called variant" from the initial variant calling so that the read counts for that tumor region can still be informative for clustering purposes. 

Is this similar approach something that is recommended when inputting mutations for CONIPHER? 

Thank you,

Aaron

P.S. Sorry if this post is not in the appropriate location--- I know it's not really an "issue" per se... Thanks

**Comment by arihueb** [comment]
Hi Aaron, apologies to have missed this. Yes, this is recommended for CONIPHER as well. In fact, all mutations must have read counts provided for every tumor sample (see also Supplementary Methods of https://doi.org/10.1038/s41596-023-00913-9).
